// AUTO-GENERATED by scripts/gen-rxdb-schemas.ts — do not edit manually.
// Source of truth: Postgres schema (supabase/migrations/)
//
// Regenerate: npm run gen

import type { RxJsonSchema } from 'rxdb/plugins/core';

export type CardsDoc = {
  id: string;
  userId: string;
  deckName: string;
  term: string;
  front?: string;
  back: string;
  tags?: string;
  created: string;
  reversible: boolean;
  order: number;
  suspended: boolean;
  approved: boolean;
};

export const cardsSchema: RxJsonSchema<CardsDoc> = {
  version: 0,
  primaryKey: 'id',
  type: 'object',
  properties: {
    id: { type: 'string', maxLength: 36 },
    userId: { type: 'string', maxLength: 36 },
    deckName: { type: 'string', maxLength: 100 },
    term: { type: 'string', maxLength: 200 },
    front: { type: 'string' },
    back: { type: 'string' },
    tags: { type: 'string' },
    created: { type: 'string' },
    reversible: { type: 'boolean' },
    order: { type: 'number' },
    suspended: { type: 'boolean' },
    approved: { type: 'boolean' },
  },
  required: ['id', 'userId', 'deckName', 'term', 'back', 'created', 'reversible', 'order', 'suspended', 'approved'],
  indexes: ['deckName'],
} as const;

export type SrsStateDoc = {
  id: string;
  userId: string;
  cardId: string;
  direction: string;
  due?: string;
  stability?: number;
  difficulty?: number;
  elapsedDays?: number;
  scheduledDays?: number;
  reps?: number;
  lapses?: number;
  state?: number;
  lastReview?: string;
};

export const srsStateSchema: RxJsonSchema<SrsStateDoc> = {
  version: 0,
  primaryKey: 'id',
  type: 'object',
  properties: {
    id: { type: 'string', maxLength: 36 },
    userId: { type: 'string', maxLength: 36 },
    cardId: { type: 'string', maxLength: 36 },
    direction: { type: 'string', maxLength: 10 },
    due: { type: 'string' },
    stability: { type: 'number' },
    difficulty: { type: 'number' },
    elapsedDays: { type: 'number' },
    scheduledDays: { type: 'number' },
    reps: { type: 'number' },
    lapses: { type: 'number' },
    state: { type: 'number' },
    lastReview: { type: 'string' },
  },
  required: ['id', 'userId', 'cardId', 'direction'],
  indexes: ['cardId'],
} as const;

export type SettingsDoc = {
  id: string;
  userId: string;
  newCardsPerDay: number;
  reviewOrder: string;
  theme: string;
};

export const settingsSchema: RxJsonSchema<SettingsDoc> = {
  version: 0,
  primaryKey: 'id',
  type: 'object',
  properties: {
    id: { type: 'string', maxLength: 36 },
    userId: { type: 'string', maxLength: 36 },
    newCardsPerDay: { type: 'number' },
    reviewOrder: { type: 'string', maxLength: 50 },
    theme: { type: 'string', maxLength: 20 },
  },
  required: ['id', 'userId', 'newCardsPerDay', 'reviewOrder', 'theme'],
} as const;

export type ReviewLogsDoc = {
  id: string;
  userId: string;
  cardId: string;
  isReverse: boolean;
  rating: number;
  state: number;
  due: string;
  stability: number;
  difficulty: number;
  elapsedDays: number;
  lastElapsedDays: number;
  scheduledDays: number;
  review: string;
};

export const reviewLogsSchema: RxJsonSchema<ReviewLogsDoc> = {
  version: 0,
  primaryKey: 'id',
  type: 'object',
  properties: {
    id: { type: 'string', maxLength: 36 },
    userId: { type: 'string', maxLength: 36 },
    cardId: { type: 'string', maxLength: 36 },
    isReverse: { type: 'boolean' },
    rating: { type: 'number' },
    state: { type: 'number' },
    due: { type: 'string' },
    stability: { type: 'number' },
    difficulty: { type: 'number' },
    elapsedDays: { type: 'number' },
    lastElapsedDays: { type: 'number' },
    scheduledDays: { type: 'number' },
    review: { type: 'string' },
  },
  required: ['id', 'userId', 'cardId', 'isReverse', 'rating', 'state', 'due', 'stability', 'difficulty', 'elapsedDays', 'lastElapsedDays', 'scheduledDays', 'review'],
} as const;

