/**
 * Generates RxDB JSON Schemas + TypeScript types from Postgres information_schema.
 * Postgres is the single source of truth.
 *
 * Usage: npx tsx scripts/gen-rxdb-schemas.ts
 * Requires local Supabase to be running.
 */
import { execSync } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';

const OUTPUT = path.resolve('src/services/rxdb-schemas.generated.ts');
const PG_URL = 'postgresql://postgres:postgres@127.0.0.1:54322/postgres';

// Config: which tables to sync, with RxDB-specific metadata.
// collection name → { table, indexes, maxLengths (for primary keys / indexed string fields) }
const SYNCED_TABLES = {
  cards: {
    table: 'cards',
    indexes: ['deckName'],
    maxLengths: { id: 300, userId: 100, deckName: 100, term: 200 },
  },
  srsState: {
    table: 'srs_state',
    indexes: ['cardId'],
    maxLengths: { id: 300, userId: 100, cardId: 300, direction: 10 },
  },
  settings: {
    table: 'settings',
    indexes: [],
    maxLengths: { id: 100, userId: 100, reviewOrder: 50, theme: 20 },
  },
  reviewLogs: {
    table: 'review_logs',
    indexes: [],
    maxLengths: { id: 300, userId: 100, cardId: 300 },
  },
} as const;

// Columns managed by replication protocol / server — excluded from RxDB schema
const EXCLUDED_COLUMNS = new Set(['_modified', '_deleted']);

interface PgColumn {
  column_name: string;
  data_type: string;
  is_nullable: string;
  column_default: string | null;
}

function queryPg(sql: string): string {
  return execSync(
    `psql "${PG_URL}" -t -A -F'\t' -c "${sql.replace(/"/g, '\\"')}"`,
    { encoding: 'utf-8' },
  ).trim();
}

function getColumns(table: string): PgColumn[] {
  const raw = queryPg(`
    SELECT column_name, data_type, is_nullable, column_default
    FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = '${table}'
    ORDER BY ordinal_position
  `);
  if (!raw) return [];
  return raw.split('\n').map((line) => {
    const [column_name, data_type, is_nullable, column_default] = line.split('\t');
    return { column_name, data_type, is_nullable, column_default: column_default || null };
  });
}

function pgTypeToJsonSchema(dataType: string): string {
  switch (dataType) {
    case 'text':
    case 'character varying':
    case 'timestamp with time zone':
    case 'uuid':
      return 'string';
    case 'integer':
    case 'bigint':
    case 'smallint':
    case 'double precision':
    case 'numeric':
    case 'real':
      return 'number';
    case 'boolean':
      return 'boolean';
    default:
      return 'string'; // fallback
  }
}

function pgTypeToTsType(dataType: string, nullable: boolean): string {
  let base: string;
  switch (dataType) {
    case 'text':
    case 'character varying':
    case 'timestamp with time zone':
    case 'uuid':
      base = 'string';
      break;
    case 'integer':
    case 'bigint':
    case 'smallint':
    case 'double precision':
    case 'numeric':
    case 'real':
      base = 'number';
      break;
    case 'boolean':
      base = 'boolean';
      break;
    default:
      base = 'string';
  }
  return nullable ? `${base} | undefined` : base;
}

function generate(): string {
  const lines: string[] = [
    '// AUTO-GENERATED by scripts/gen-rxdb-schemas.ts — do not edit manually.',
    '// Source of truth: Postgres schema (supabase/migrations/)',
    '//',
    '// Regenerate: npm run gen',
    '',
    "import type { RxJsonSchema } from 'rxdb/plugins/core';",
    '',
  ];

  const collectionEntries: string[] = [];

  for (const [collectionName, config] of Object.entries(SYNCED_TABLES)) {
    const columns = getColumns(config.table).filter(
      (c) => !EXCLUDED_COLUMNS.has(c.column_name),
    );

    if (columns.length === 0) {
      console.error(`No columns found for table ${config.table}`);
      process.exit(1);
    }

    // TypeScript type
    const typeName = collectionName.charAt(0).toUpperCase() + collectionName.slice(1) + 'Doc';
    lines.push(`export type ${typeName} = {`);
    for (const col of columns) {
      const nullable = col.is_nullable === 'YES';
      const tsType = pgTypeToTsType(col.data_type, nullable);
      const optional = nullable ? '?' : '';
      lines.push(`  ${col.column_name}${optional}: ${tsType.replace(' | undefined', '')};`);
    }
    lines.push('};');
    lines.push('');

    // JSON Schema
    const schemaName = collectionName + 'Schema';
    const required = columns
      .filter((c) => c.is_nullable === 'NO')
      .map((c) => `'${c.column_name}'`);

    lines.push(`export const ${schemaName}: RxJsonSchema<${typeName}> = {`);
    lines.push('  version: 0,');
    lines.push("  primaryKey: 'id',");
    lines.push("  type: 'object',");
    lines.push('  properties: {');
    for (const col of columns) {
      const jsonType = pgTypeToJsonSchema(col.data_type);
      const maxLength = (config.maxLengths as Record<string, number>)[col.column_name];
      if (maxLength) {
        lines.push(`    ${col.column_name}: { type: '${jsonType}', maxLength: ${maxLength} },`);
      } else {
        lines.push(`    ${col.column_name}: { type: '${jsonType}' },`);
      }
    }
    lines.push('  },');
    lines.push(`  required: [${required.join(', ')}],`);
    if (config.indexes.length > 0) {
      lines.push(`  indexes: [${config.indexes.map((i) => `'${i}'`).join(', ')}],`);
    }
    lines.push('} as const;');
    lines.push('');

    collectionEntries.push(`  ${collectionName}: { schema: ${schemaName}, type: ${typeName} }`);
  }

  return lines.join('\n') + '\n';
}

const output = generate();
fs.writeFileSync(OUTPUT, output);
console.log(`Generated ${OUTPUT}`);
