/**
 * One-time migration: GitHub repo cards.json → Supabase Postgres (UUID PKs)
 *
 * Usage:
 *   npx tsx scripts/migrate-from-github.ts <userId> <github-repo-url>
 *
 * Requires SUPABASE_URL and SUPABASE_SERVICE_KEY env vars.
 */
import { createClient } from '@supabase/supabase-js';

const userId = process.argv[2];
const repoUrl = process.argv[3];

if (!userId || !repoUrl) {
  console.error('Usage: npx tsx scripts/migrate-from-github.ts <userId> <github-repo-url>');
  process.exit(1);
}

const supabaseUrl = process.env.SUPABASE_URL || 'http://127.0.0.1:54321';
const supabaseKey = process.env.SUPABASE_SERVICE_KEY || process.env.SUPABASE_ANON_KEY || '';
if (!supabaseKey) {
  console.error('Set SUPABASE_SERVICE_KEY (or SUPABASE_ANON_KEY for local) env var');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

const match = repoUrl.match(/github\.com\/([^/]+)\/([^/]+)/);
if (!match) { console.error('Invalid GitHub URL'); process.exit(1); }
const [, owner, repo] = match;

interface CardJSON {
  front?: string;
  back: string;
  tags?: string[];
  created: string;
  reversible?: boolean;
  state: Record<string, unknown> | null;
  reverseState: Record<string, unknown> | null;
  suspended?: boolean;
}

async function fetchDeck(deckName: string): Promise<Record<string, CardJSON>> {
  const res = await fetch(
    `https://api.github.com/repos/${owner}/${repo}/contents/${deckName}/cards.json`,
    { headers: { Accept: 'application/vnd.github.v3.raw' } },
  );
  if (!res.ok) throw new Error(`Failed to fetch ${deckName}: ${res.status}`);
  return res.json();
}

async function migrate() {
  const res = await fetch(`https://api.github.com/repos/${owner}/${repo}/contents/`);
  const entries = await res.json() as Array<{ name: string; type: string }>;
  const decks = entries.filter(e => e.type === 'dir' && !e.name.startsWith('.'));

  console.log(`Found ${decks.length} deck(s): ${decks.map(d => d.name).join(', ')}`);

  for (const deck of decks) {
    const deckName = deck.name;
    console.log(`\nMigrating deck: ${deckName}`);

    const cardsJson = await fetchDeck(deckName);
    const terms = Object.keys(cardsJson).filter(k => !k.startsWith('$'));
    console.log(`  ${terms.length} cards`);

    // Insert cards (UUIDs auto-generated by Postgres) and get them back
    const cardRows = terms.map((term, index) => {
      const card = cardsJson[term];
      return {
        userId,
        deckName,
        term,
        front: card.front ?? null,
        back: card.back,
        tags: JSON.stringify(card.tags ?? []),
        created: card.created,
        reversible: card.reversible ?? false,
        order: index,
        suspended: card.suspended ?? false,
        approved: true,
      };
    });

    const { data: insertedCards, error: cardsError } = await supabase
      .from('cards')
      .upsert(cardRows, { onConflict: 'userId,deckName,term' })
      .select('id, term');
    if (cardsError) {
      console.error('  Cards insert failed:', cardsError.message);
      continue;
    }
    console.log(`  ✓ ${insertedCards.length} cards inserted`);

    // Build term → UUID map
    const termToId = new Map(insertedCards.map((c: any) => [c.term, c.id]));

    // Build srs_state rows using the UUID card IDs
    const srsRows: Array<Record<string, unknown>> = [];
    for (const term of terms) {
      const card = cardsJson[term];
      const cardId = termToId.get(term);
      if (!cardId) continue;

      if (card.state) {
        srsRows.push({
          userId,
          cardId,
          direction: 'forward',
          due: card.state.due as string,
          stability: card.state.stability,
          difficulty: card.state.difficulty,
          elapsedDays: card.state.elapsed_days,
          scheduledDays: card.state.scheduled_days,
          reps: card.state.reps,
          lapses: card.state.lapses,
          state: card.state.state,
          lastReview: card.state.last_review as string | undefined,
        });
      }

      if (card.reverseState) {
        srsRows.push({
          userId,
          cardId,
          direction: 'reverse',
          due: card.reverseState.due as string,
          stability: card.reverseState.stability,
          difficulty: card.reverseState.difficulty,
          elapsedDays: card.reverseState.elapsed_days,
          scheduledDays: card.reverseState.scheduled_days,
          reps: card.reverseState.reps,
          lapses: card.reverseState.lapses,
          state: card.reverseState.state,
          lastReview: card.reverseState.last_review as string | undefined,
        });
      }
    }

    console.log(`  ${srsRows.length} SRS state rows`);

    if (srsRows.length > 0) {
      const { error: srsError } = await supabase
        .from('srs_state')
        .upsert(srsRows, { onConflict: 'cardId,direction' });
      if (srsError) {
        console.error('  SRS state insert failed:', srsError.message);
        continue;
      }
      console.log(`  ✓ ${srsRows.length} SRS state rows inserted`);
    }
  }

  console.log('\nDone!');
}

migrate().catch((err) => {
  console.error('Migration failed:', err);
  process.exit(1);
});
